#!/usr/bin/env python3
"""FICSIT Foreman bundler — one source (lib/*.lua), two distributions.

Emits, from lib/{router,planner,namer,app}.lua:
  dist/foreman.lua       FULL single-chunk bundle (fetched by the Internet Card,
                         load()ed in-game). Returns { version, run(topology,opts) }.
                         Ends with a --[[FOREMAN_EOF]] marker so the bootstrap can
                         detect a truncated fetch.
  dist/foreman-lite.lua  The LITE EEPROM: embedded LITE modules (router/planner/app,
                         no namer) + the upgrade bootstrap (detect Internet Card ->
                         fetch FULL at the pinned tag -> run; else run embedded LITE).
                         Paste into an EEPROM; set FOREMAN_TOPOLOGY / edit TOPOLOGY.

No code is stripped (ample EEPROM headroom); each module ends in `return <table>`
so wrapping its source verbatim in `function() ... end` yields that table.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIB = os.path.join(ROOT, "lib")
DIST = os.path.join(ROOT, "dist")
OWNER = os.environ.get("FOREMAN_OWNER", "ErikTMA")
REPO = os.environ.get("FOREMAN_REPO", "ficsit-foreman")

EOF_MARKER = "--[[FOREMAN_EOF]]"


def read(name):
    with open(os.path.join(LIB, name), encoding="utf-8") as fh:
        return fh.read().rstrip("\n")


def version():
    p = os.path.join(ROOT, "VERSION")
    return open(p, encoding="utf-8").read().strip() if os.path.exists(p) else "0.0.0"


def preload(names):
    """Emit a local require shim + one _preload entry per module (verbatim body)."""
    out = [
        "local _preload, _cache = {}, {}",
        "local function require(n)",
        "  if _cache[n] then return _cache[n] end",
        "  local m = _preload[n](); _cache[n] = m; return m",
        "end",
    ]
    for n in names:
        out.append('_preload["%s"] = function()' % n)
        out.append(read(n + ".lua"))
        out.append("end")
    return "\n".join(out)


def emit_full(ver):
    body = f"""-- FICSIT Foreman — FULL bundle v{ver}
-- GENERATED by tools/bundle.py. Fetched by the LITE EEPROM's Internet-Card bootstrap.
{preload(["router", "planner", "namer", "app"])}
return {{
  version = "{ver}",
  run = function(topology, opts)
    opts = opts or {{}}
    if opts.autoname == nil then opts.autoname = true end
    return require("app").run(
      {{ Router = require("router"), Planner = require("planner"), Namer = require("namer") }},
      topology, opts)
  end,
}}
{EOF_MARKER}
"""
    return body


def emit_lite(ver):
    base = f"https://raw.githubusercontent.com/{OWNER}/{REPO}/"
    body = f"""-- ============================================================================
-- FICSIT Foreman — LITE EEPROM  v{ver}   (GENERATED by tools/bundle.py)
-- Paste this whole file into a Computer Case EEPROM.
-- 1) Declare your factory in the TOPOLOGY table below (see examples/topology.example.lua)
--    OR set a global FOREMAN_TOPOLOGY before this runs.
-- 2) It runs LITE standalone. Once an Internet Card is unlocked, it auto-fetches
--    the FULL build from the pinned release and runs that instead.
-- ============================================================================
local PIN  = "v{ver}"
local BASE = "{base}" .. PIN .. "/dist/"

-- >>> EDIT: your factory topology (replace `nil`), or set global FOREMAN_TOPOLOGY <<<
local TOPOLOGY = FOREMAN_TOPOLOGY or nil

-- ---- embedded LITE modules (router, planner, app — no namer) ----------------
{preload(["router", "planner", "app"])}

local function runLite()
  computer.log(1, "[Foreman] LITE running (" .. PIN .. ")")
  return require("app").run(
    {{ Router = require("router"), Planner = require("planner") }}, TOPOLOGY, {{ autoname = false }})
end

-- ---- bootstrap: upgrade to FULL when an Internet Card is present ------------
local function fetchFull()
  local card = computer.getPCIDevices(classes.FINInternetCard)[1]
  if not card then return nil end
  computer.log(1, "[Foreman] Internet Card found; fetching FULL " .. PIN .. " ...")
  local ok, req = pcall(function() return card:request(BASE .. "foreman.lua", "GET", "") end)
  if not ok or not req then return nil end
  local deadline = computer.millis() + 10000
  while not req:canGet() do
    if computer.millis() > deadline then
      computer.log(3, "[Foreman] fetch timeout; staying on LITE"); return nil
    end
    coroutine.yield()
  end
  local code, full_body = req:get()
  if code ~= 200 or type(full_body) ~= "string" or #full_body == 0 then
    computer.log(3, "[Foreman] fetch HTTP " .. tostring(code) .. "; staying on LITE"); return nil
  end
  if not full_body:find("{EOF_MARKER}", 1, true) then
    computer.log(3, "[Foreman] fetch truncated (no EOF marker); staying on LITE"); return nil
  end
  local fn, err = load(full_body, "@foreman/full", "t", _G)
  if not fn then
    computer.log(3, "[Foreman] FULL compile error: " .. tostring(err) .. "; staying on LITE"); return nil
  end
  local ok2, full = pcall(fn)
  if not ok2 or type(full) ~= "table" or type(full.run) ~= "function" then
    computer.log(3, "[Foreman] FULL load error; staying on LITE"); return nil
  end
  return full
end

-- ---- main ------------------------------------------------------------------
if not TOPOLOGY then
  computer.log(4, "[Foreman] no TOPOLOGY declared — edit the TOPOLOGY table at the top, or set FOREMAN_TOPOLOGY.")
  return
end
local full = fetchFull()
if full then
  computer.log(1, "[Foreman] FULL " .. tostring(full.version) .. " running")
  full.run(TOPOLOGY, {{ autoname = true }})
else
  runLite()
end
"""
    return body


def main():
    ver = version()
    os.makedirs(DIST, exist_ok=True)
    full = emit_full(ver)
    lite = emit_lite(ver)
    with open(os.path.join(DIST, "foreman.lua"), "w", encoding="utf-8") as fh:
        fh.write(full)
    with open(os.path.join(DIST, "foreman-lite.lua"), "w", encoding="utf-8") as fh:
        fh.write(lite)
    print(f"bundled v{ver}: dist/foreman.lua ({len(full)}B), dist/foreman-lite.lua ({len(lite)}B)")
    if len(lite) > 50000:
        print("WARNING: foreman-lite.lua exceeds 50KB EEPROM sanity ceiling", file=sys.stderr)


if __name__ == "__main__":
    main()
