#!/usr/bin/env python3
"""FICSIT Foreman bundler — one source (lib/*.lua), three artifacts.

LITE and FULL are SEPARATE, independently-versioned products. LITE never fetches
or upgrades itself; FULL is installed deliberately via its own loader once the
Internet Card is unlocked.

Versions come from the VERSION file:
    lite=<x.y.z>
    full=<x.y.z>

Artifacts (in dist/):
  foreman-lite.lua    Standalone LITE EEPROM (router/planner/app; no namer, no
                      fetch). Paste it, set TOPOLOGY, done. Header: "LITE v<lite>".
  foreman.lua         FULL bundle (all modules). Returns { version=<full>, run }.
                      Ends with --[[FOREMAN_EOF]] (truncated-fetch guard). Fetched.
  foreman-loader.lua  FULL loader EEPROM: requires an Internet Card, fetches
                      foreman.lua from the pinned tag (v<full>), runs it. Does NOT
                      fall back to LITE — they are distinct products.

No code is stripped; each module ends in `return <table>`, so wrapping its source
in `function() ... end` yields that table.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIB = os.path.join(ROOT, "lib")
DIST = os.path.join(ROOT, "dist")
OWNER = os.environ.get("FOREMAN_OWNER", "ErikTMA")
REPO = os.environ.get("FOREMAN_REPO", "ficsit-foreman")
EOF_MARKER = "--[[FOREMAN_EOF]]"


def read(name):
    with open(os.path.join(LIB, name), encoding="utf-8") as fh:
        return fh.read().rstrip("\n")


def versions():
    out = {"lite": "0.0.0", "full": "0.0.0"}
    p = os.path.join(ROOT, "VERSION")
    if os.path.exists(p):
        for line in open(p, encoding="utf-8"):
            line = line.strip()
            if "=" in line:
                k, v = line.split("=", 1)
                out[k.strip()] = v.strip()
    return out


def preload(names):
    """A local require shim + one _preload entry per module (verbatim body)."""
    out = [
        "local _preload, _cache = {}, {}",
        "local function require(n)",
        "  if _cache[n] then return _cache[n] end",
        "  local m = _preload[n](); _cache[n] = m; return m",
        "end",
    ]
    for n in names:
        out.append('_preload["%s"] = function()' % n)
        out.append(read(n + ".lua"))
        out.append("end")
    return "\n".join(out)


def emit_lite(ver):
    return f"""-- ============================================================================
-- FICSIT Foreman — LITE EEPROM  v{ver}   (GENERATED by tools/bundle.py)
-- Standalone early-game controller. No Internet Card, no hard drive, no upgrades.
-- Paste this whole file into a Computer Case EEPROM, then declare your factory in
-- the TOPOLOGY table below (see examples/topology.example.lua) and hand-name your
-- containers <Item>_<Keyword>_<N>. To run the FULL build later, paste the separate
-- foreman-loader.lua instead — LITE and FULL are independent, separately-versioned.
-- ============================================================================
local LITE_VERSION = "{ver}"

-- Paste-and-go: leave TOPOLOGY nil and the controller auto-discovers the belt graph
-- (crawls getFactoryConnectors -> getConnected -> owner) and reads each container's
-- role/item/target from its nick. Only set a TOPOLOGY table if you want to declare it
-- by hand (or set the global FOREMAN_TOPOLOGY).
local TOPOLOGY = FOREMAN_TOPOLOGY or nil

{preload(["discover", "router", "planner", "namer", "app"])}

computer.log(1, "[Foreman] LITE v" .. LITE_VERSION ..
  (TOPOLOGY and " running (declared topology)" or " running (auto-discovering topology)"))
require("app").run({{ Router = require("router"), Planner = require("planner"),
  Namer = require("namer"), Discover = require("discover") }}, TOPOLOGY, {{}})
"""


def emit_full(ver):
    return f"""-- FICSIT Foreman — FULL bundle v{ver}   (GENERATED by tools/bundle.py)
-- Fetched and run by foreman-loader.lua (Internet Card). Returns {{ version, run }}.
-- A nil topology triggers auto-discovery (crawl the belt graph + read nicks).
{preload(["discover", "router", "planner", "namer", "app"])}
return {{
  version = "{ver}",
  run = function(topology, opts)
    opts = opts or {{}}
    if opts.autoname == nil then opts.autoname = true end
    return require("app").run(
      {{ Router = require("router"), Planner = require("planner"),
        Namer = require("namer"), Discover = require("discover") }},
      topology, opts)
  end,
}}
{EOF_MARKER}
"""


def emit_loader(full_ver):
    base = f"https://raw.githubusercontent.com/{OWNER}/{REPO}/"
    return f"""-- ============================================================================
-- FICSIT Foreman — FULL loader EEPROM   (GENERATED by tools/bundle.py)
-- A tiny, STABLE EEPROM: paste it once. To upgrade OR downgrade the FULL build,
-- just change the VERSION line below in the in-game EEPROM editor — it re-fetches
-- that exact version on the next run. Pin any released FULL version.
-- REQUIRES an Internet Card; it does NOT fall back to LITE (LITE/FULL are separate).
-- ============================================================================

-- >>> CHANGE THIS to upgrade/downgrade FULL (any released version tag, no 'v') <<<
local VERSION = "{full_ver}"

-- Paste-and-go: leave TOPOLOGY nil and FULL auto-discovers the belt graph + reads
-- container nicks. Only set it to declare the topology by hand (or FOREMAN_TOPOLOGY).
local TOPOLOGY = FOREMAN_TOPOLOGY or nil

local URL = "{base}" .. "v" .. VERSION .. "/dist/foreman.lua"

local function fetchFull()
  local card = computer.getPCIDevices(classes.FINInternetCard)[1]
  if not card then
    computer.log(4, "[Foreman] FULL loader needs an Internet Card. Use foreman-lite.lua until then.")
    return nil
  end
  computer.log(1, "[Foreman] fetching FULL v" .. VERSION .. " ...")
  local ok, req = pcall(function() return card:request(URL, "GET", "") end)
  if not ok or not req then computer.log(3, "[Foreman] request failed"); return nil end
  local deadline = computer.millis() + 10000
  while not req:canGet() do
    if computer.millis() > deadline then computer.log(3, "[Foreman] fetch timeout"); return nil end
    coroutine.yield()
  end
  local code, body = req:get()
  if code ~= 200 or type(body) ~= "string" or #body == 0 then
    computer.log(3, "[Foreman] fetch HTTP " .. tostring(code)); return nil
  end
  if not body:find("{EOF_MARKER}", 1, true) then
    computer.log(3, "[Foreman] fetch truncated (no EOF marker)"); return nil
  end
  local fn, err = load(body, "@foreman/full", "t", _G)
  if not fn then computer.log(3, "[Foreman] FULL compile error: " .. tostring(err)); return nil end
  local ok2, full = pcall(fn)
  if not ok2 or type(full) ~= "table" or type(full.run) ~= "function" then
    computer.log(3, "[Foreman] FULL load error"); return nil
  end
  return full
end

local full = fetchFull()
if not full then return end
computer.log(1, "[Foreman] FULL " .. tostring(full.version) ..
  (TOPOLOGY and " running (declared topology)" or " running (auto-discovering topology)"))
full.run(TOPOLOGY, {{ autoname = true }})
"""


def main():
    v = versions()
    os.makedirs(DIST, exist_ok=True)
    arts = {
        "foreman-lite.lua": emit_lite(v["lite"]),
        "foreman.lua": emit_full(v["full"]),
        "foreman-loader.lua": emit_loader(v["full"]),
    }
    for name, body in arts.items():
        with open(os.path.join(DIST, name), "w", encoding="utf-8") as fh:
            fh.write(body)
        if name.endswith("-lite.lua") and len(body) > 50000:
            print(f"WARNING: {name} exceeds 50KB EEPROM ceiling ({len(body)}B)", file=sys.stderr)
    print(f"bundled LITE v{v['lite']} ({len(arts['foreman-lite.lua'])}B), "
          f"FULL v{v['full']} ({len(arts['foreman.lua'])}B), "
          f"loader ({len(arts['foreman-loader.lua'])}B)")


if __name__ == "__main__":
    main()
